### ISSUE TITLE
🦸Hero Image

### ISSUE THREAD

**Issue by JustinLung** [DaanKorver/fdnd-programma-microsite-autonomous#1]
Als gebruiker wil ik een hero image zien, zodat ik me verwelkomd voel wanneer ik op de website kom.

- [x] Hero image toevoegen
- [x] FDND shape toevoegen
- [x] FDND logo toevoegen bij de shapes
- [x] FDND Title toevoegen bij de shapes
- [x] Definition of done

**Comment by JustinLung** [comment]
@DaanKorver Ready For Testing

**Comment by DaanKorver** [comment]
Hi @JustinLung , looks good but got a few points.
1. Dont use a span as a standalone element, in this situation you could use a div
2. Try not to use id's in CSS as they have higher priority which makes it harder to write/overwritte css later on

GL👍

**Comment by JustinLung** [comment]
Fixed issue @DaanKorver 

ebad477d7aaacacb3ad6b3b2fb229a8120d1ec3e

**Comment by DaanKorver** [comment]
LGTM! Ready for merge

**Comment by JustinLung** [comment]
Done! ;p
