### ISSUE TITLE
🦴 CSS Variables

### ISSUE THREAD

**Issue by DaanKorver** [DaanKorver/fdnd-programma-microsite-autonomous#11]
Als developer wil ik CSS variables zodat ik makkelijk kleuren kan aanpassen

- [x] Alle kleuren uit de styleguide als variables
- [x] Font size variables
- [x] Border radius variables
- [x] Shadow variables
- [x] Definition of done

**Comment by DaanKorver** [comment]
@JustinLung Quick check please

**Comment by JustinLung** [comment]
LGTM! @DaanKorver

**Comment by DaanKorver** [comment]
Done f3b6177c0b1614896b4f09c6ac768977d03a2662
