### ISSUE TITLE
💻 Semester: 1 koloms layout

### ISSUE THREAD

**Issue by JustinLung** [DaanKorver/fdnd-programma-microsite-autonomous#3]
Als gebruiker, wil ik de semesters in een 1 koloms layout zien, zodat ik een overzicht krijg van alle semesters.

Requirements:
- [x] Content moet echt zijn
- [x] Image toevoegen aan het grid semester
- [x] Button voor meer informatie
- [x] 1 kolom layout
- [x] Definition of done

**Comment by JustinLung** [comment]
@DaanKorver Ready for testing! ;)

**Comment by DaanKorver** [comment]
@JustinLung Looks good, ready for merge
