### ISSUE TITLE
🖼 Modaal venster met sprints

### ISSUE THREAD

**Issue by DaanKorver** [DaanKorver/fdnd-programma-microsite-autonomous#4]
Als gebruiker wil ik een modaal venster met een overzicht van de sprints zodat ik een duidelijk overzicht heb met informatie over de sprints.

Requirements
- [ ] #14
- [x] Sluit knop om alle modaal vensters te sluiten
- [x] Informatie over de sprints
- [x] Animatie wanneer je het modaal venster opent en sluit
- [x] Links naar de live producten
- [x] Definition of done

- [x] Bij de sprints moet er de volgende onderwerpen aanbod komen:
1.  Beschrijving
2. Datum
3. Semester
4. Topics (inhoud)

**Comment by DaanKorver** [comment]
@JustinLung Ready for test!

**Comment by JustinLung** [comment]
Still has one #ffff @DaanKorver fix this ;)

**Comment by DaanKorver** [comment]
Done b2ccab3c686659ed4109a958450c4b1d55ae1958
