### ISSUE TITLE
📠 Opdrachten / Leertaken

### ISSUE THREAD

**Issue by JustinLung** [DaanKorver/fdnd-programma-microsite-autonomous#7]
Als gebruiker wil ik informatie van de opdrachten en leertaken lezen, zodat ik weet wat de verwachtingen zijn van de opdrachten. 

Requirements:
- [x] Informatie over opdrachten & leertaken
- [x] Beeldmateriaal doormiddel van foto, icon of logo
- [x] Definition of done

**Comment by JustinLung** [comment]
@DaanKorver Ready for testing ;)

**Comment by JustinLung** [comment]
Redesign made ready for testing!

**Comment by DaanKorver** [comment]
Done, ready for merge @JustinLung
