### ISSUE TITLE
🎟️ JSON object

### ISSUE THREAD

**Issue by DaanKorver** [DaanKorver/fdnd-programma-microsite-autonomous#8]
Als developer wil ik makkelijk de content van de site kunnen vullen doormiddel van JSON zodat ik makkelijk content dynamisch kan aanpassen.

Requirements
- [x] Simpele object structuur
- [x] Bevat: beschrijving, datum, semester, topics, uitgewerkte opdrachten.
- [x] Functie om de JSON op te halen.
- [x] Definition of done

**Comment by DaanKorver** [comment]
@JustinLung Ready for test 🎈

**Comment by JustinLung** [comment]
LGTM! @DaanKorver

**Comment by DaanKorver** [comment]
Done! 24332c0829c133c77b543b4b2b753f382dcfb1b8
