### ISSUE TITLE
🏔️ Header

### ISSUE THREAD

**Issue by JustinLung** [DaanKorver/fdnd-programma-microsite-autonomous#9]
Als gebruiker wil ik een header zien dat een logo bevat van de Hogeschool van Amsterdam, zodat ik weet dat opleiding onderdeel van de hogeschool is.

Requirements
- [x] Logo HvA
- [x] Definition of done

**Comment by devabdurabi** [comment]
Ready for testing!

**Comment by JustinLung** [comment]
LGTM!

**Comment by JustinLung** [comment]
Ready for merge

**Comment by JustinLung** [comment]
Use a different tag for the text instead of a div. 

HTML: 
 `` <div class="fdnd">
    Frontend <br>Design & Development
</div>
``

CSS try to use REM's instead of px's for padding & margins.

  margin-top: -18px;
  margin-left: 0.3em;

Why use different units? Try to use the same units for consistency.

**Comment by devabdurabi** [comment]
I made some elements changes for semantic html. I also changed my margins and paddings units.

**Comment by JustinLung** [comment]
Ready for merge

**Comment by devabdurabi** [comment]
Done
